print("Welcome to Tic Tac Toe!")
ans=input("Do you want to be X or 0?")
print("Computer will go first.")
print('    ',"|",'   ',"|",'    ')
print('    ',"|",'   ',"|",'    ')
print('    ',"|",'   ',"|",'    ')
print('----------------')
print('    ',"|",'   ',"|",'    ')
print('    ',"|",'   ',"|",'    ')
print('    ',"|",'   ',"|",'    ')
print('----------------')
print('    ',"|",'   ',"|",'    ')
print('    ',"|",'   ',"|",'    ')
print('    ',"|",'   ',"|",'    ')


print('Hello!')